Update README.md with instructions to live_grep todos
nvim-neorg/neorg-telescope pull request #47
Opened 2024-01-05 17:15 UTC by champignoom

2024-01-05 19:07 UTC, max397574 requested changes
1. will this work ootb or require e.g. ripgrep? and a certain matcher?
2. would be really cool if you could automatically detect the current workspace (either just in the keymapping or in the function itself)
if you don't know how tell me and I'll search a snippet for you (you should be able to find plenty in this repo)

2024-01-05 19:07 UTC, max397574 commented on README.md
> +     require('telescope.builtin').live_grep{cwd=dir}
```suggestion
     require('telescope.builtin').live_grep{ cwd = dir }
```
format please

2024-01-05 19:07 UTC, max397574 commented on README.md
> +function get_todos(dir, states)
```suggestion
local function get_todos(dir, states)
```

2024-01-05 19:07 UTC, max397574 commented on README.md
> +-- You can now use `:lua get_todos('~/notes', '[^x_]')` to get all todo items inside directory '~/notes' that are not yet done or cancelled.
```suggestion
```
mapping is enough
if anything more then a command
we don't want users to have to call lua functions like this

2024-01-05 19:07 UTC, max397574 commented on README.md
> +-- Or, to bind it to a key, like ctrl_t:
```suggestion
-- This can be bound to a key
```

2024-01-06 10:27 UTC, champignoom commented
done and done

2024-01-06 18:53 UTC, max397574 commented on README.md
> +    local current_workspace = dirman.get_current_workspace()
needs to be inside the function
otherwise it won't work if you switch workspaces

2024-01-06 18:54 UTC, max397574 approved these changes

2024-04-19 17:40 UTC, merged