feat: ws relative file/header backlink pickers
nvim-neorg/neorg-telescope pull request #50
Opened 2024-02-08 21:51 UTC by benlubas

closes #49

This is the "backlink picker at home". It's a simple, incomplete, implementation that is "good enough".

It *does*:
- find workspace relative backlinks to the current file or header
- uses `rg` regex to find links
- uses lua patterns to find the current heading (searches up until it hits one)

It *does not*:
- handle relative path links
- use TS to find the current heading

I, and others want a simple backlink functionality now while we wait for these features to be properly implemented in Neorg. So that's what this is, something to hold us over while we wait for the real thing.

2024-02-08 22:08 UTC, benlubas commented
Oh, still have to add docs. will do that later tonight

2024-02-09 04:27 UTC, benlubas commented
This is now ready to be merged (pending review)

2024-02-10 10:11 UTC, max397574 requested changes

2024-02-10 10:11 UTC, max397574 commented on .editorconfig
> +
nice addition ig
is that empty line some sort of convention?
if not please remove

2024-02-10 10:11 UTC, max397574 commented on README.md
> +![search backlink](https://github.com/benlubas/neorg-telescope/assets/56943754/1332f319-cf43-4a5b-902a-f2bbe4ea14e3)
just wondering
will this still work if your fork no longer exists?
perhaps just put the video in an issue in this repo and copy the link there
no clue how the github media things work these days

2024-02-10 10:11 UTC, max397574 commented on README.md
> +### Search File and Heading Backlinks
mention the commands `Telescope neorg ...` somewhere

2024-02-10 10:11 UTC, max397574 commented on README.md
> +
formatting

2024-02-10 10:11 UTC, max397574 commented on lua/telescope/_extensions/neorg/backlinks/file_backlinks.lua
> +local file_backlink_regex = require("telescope._extensions.neorg.backlinks.utils")
I really don't like this
either name the file correctly to what it is or return a table part of which is this regex
I'd really much prefer the second option
also in other file

2024-02-10 10:11 UTC, max397574 commented on lua/telescope/_extensions/neorg/backlinks/file_backlinks.lua
> +local function get_current_workspace()
I feel like we got this function duplicated at quite a few places
perhaps extract it in the utils module here https://github.com/nvim-neorg/neorg-telescope/blob/main/lua/neorg/telescope_utils.lua

2024-02-10 14:37 UTC, max397574 approved these changes

2024-02-10 14:37 UTC, merged